version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: go
    ports:
      - 3000:3000
    volumes:
      - ./app:/go/src/app
    tty: true
    # command: fresh
  web:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
#   db:
#     container_name: mysql
#     build:
#       context: .
#       dockerfile: ./docker/db/Dockerfile
#     ports:
#       - 3306:3306
#     environment:
#       MYSQL_DATABASE: database
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#       MYSQL_ROOT_PASSWORD: password
#       TZ: 'Asia/Tokyo'
#     volumes:
#       - mysql-volume:/var/lib/mysql

# volumes:
#   mysql-volume: